import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Provider from '../context/Provider'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Provider>

    <html lang="en">
      <head>
        <title>Nikita</title>

        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;600&family=Unbounded:wght@400;500;600&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
    </Provider>
  );
}
